<div class="page-header">
	<h1>Administration</h1>
</div>

<div class="row">
	<div class="col-lg-2">	
		<ul class="nav nav-pills nav-stacked nav-fixed-left">
		  <li role="presentation"><a href="<?php echo APP_URL ?>/admin/settings"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
		  <li role="presentation"><a href="<?php echo APP_URL ?>/admin/collections"><span class="glyphicon glyphicon-music"></span> Collections</a></li>
		  <li role="presentation"><a href="<?php echo APP_URL ?>/admin/users"><span class="glyphicon glyphicon-user"></span> Users</a></li>
		  <li role="presentation"><a href="<?php echo APP_URL ?>/admin/recordings"><span class="glyphicon glyphicon glyphicon-cd"></span> Recordings</a></li>
		  <li role="presentation"><a><span class="glyphicon glyphicon-bullhorn"></span> Sensors</a></li>
		  <li role="presentation"><a><span class="glyphicon glyphicon-export"></span> Export</a></li>
		  <li role="presentation"><a><span class="glyphicon glyphicon-star"></span> Quality Control</a></li>
		  <!--li role="presentation"><a href="admin/weather"><span class="glyphicon glyphicon-cloud"></span> Weather Data</a></li-->

		  <div class="panel-group" role="tablist"> 
			  <div class="panel panel-default menu"> 
				  <div class="panel-heading" role="tab" id="collapseListGroupHeading1"> 
						  <a href="#collapseListGroup1" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="collapseListGroup1"><span class="glyphicon glyphicon-wrench"></span> Maintenance <span class="caret"></span></a>
				  </div> 
				  <div aria-expanded="true" class="panel-collapse collapse" role="tabpanel" id="collapseListGroup1" aria-labelledby="collapseListGroupHeading1"> 
					  <ul class="list-group">
                        <li><a class="list-group-item">Check Database</a></li>
                        <li><a class="list-group-item">Clear Cache</a></li>
						<li><a class="list-group-item">Generate Files</a></li>
					  </ul> 
				  </div> 
			 </div> 
		  </div>
		</ul>
	</div>
	
	<div class="col-lg-10">	
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->sectionTitle;?></h3>
			</div>
			<div class="panel-body">
				<?php echo $this->section;?>
			</div>
		</div>
	</div>			
</div>
