<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="<?php echo APP_URL; ?>/ajaxcallmanager.php?class=tag&action=save" class="async_form">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Call Distance Estimation</h4>
				</div>
				<div class="modal-body">					
						<input name="<?php echo $this->tagIdLabel;?>" type="hidden" value="<?php echo $this->tagId;?>">
						<div class="form-group">						
							<label for="<?php echo $this->callDistLabel;?>">Introduce Call Distance Estimation</label>		
							<input class="form-control" id="call_distance" name="<?php echo $this->callDistLabel;?>" type="number">	
							<div class="checkbox" id="dist_check">
								<label><input id='distance_not_estimable' name="distance_not_estimable" type="checkbox"> Distance not estimable</label>
							</div>
						</div> 
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>	
				</div>
			</form>
		</div>
	</div>
</div>
<script>
	$(".async_form").submit(function(e){
	  submitAsyncForm(this, e);
	  $('#modal-div').modal('hide');
	});
	
	$('#call_distance').change( function() {
	  if($(this).val() == null )
	    $('#distance_not_estimable').prop( 'checked', true );
	  else
	    $('#distance_not_estimable').prop( 'checked', false );
	});
	
	$('#distance_not_estimable').click( function() {
	  $('#call_distance').val(null);
	  
	  if($('#distance_not_estimable').is(':checked')){
	    $("#call_distance").prop("readonly", true);
	  }	
	  else {
	    $("#call_distance").prop("readonly", false);
	  }
	});
</script>
