<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Upload Sound Files</h4>
			</div>
			<div class="modal-body">
				<div id="file_uploader" class="file-upload">You browser doesn't support native upload.</div>
				<form id="fileForm">					
					<label id="upload_message"></label>
					<input type="hidden" name="colID" value="<?php echo $this->colID;?>">
					<button id="save_button" type="submit" class="btn btn-primary" disabled>Save</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	$(function() {
		$("#file_uploader").plupload({
			runtimes : 'html5',
			url : '<?php echo APP_URL;?>/uploaded.php',
			max_file_size : '1000mb',
			chunk_size : '1mb',
			unique_names : false,
			filters : {
				max_file_size : '1000mb',
				mime_types: [
					{title : "Sound files", extensions : "flac,wav,ogg,mp3"}
				]
			},
			init : {	 
				UploadComplete: function(up, files) {
					$("#save_button").prop('disabled', false);
					$("#upload_message").html("Files Uploaded");
					
				},	  
				Error: function(up, args) {
					alert("An Error has ocurred.");
				}
			}
		});
		
		$('#fileForm').submit(function(e){
			$('#save_button').prop('disabled', true);
			
			$.ajax({
				type: 'POST',
				url: 'ajaxcallmanager.php?class=file&action=save',
				data: $(this).serialize(),
				success: function(data){
					$('#modal-div').modal('hide');	
			    },
			    error: function(data, error, message){
					showMessage(message, true);
					$('#modal-div').modal('hide');
			    }
			});
			e.preventDefault();
		});			
		
	});
</script>
