<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<h6>Developed by <a href="http://www.crazycodelady.com" target="_blank" title="CrazyCodeLady. Noemi Perez">CrazyCodeLady - Noemi Perez</a></h6>
				<h6>"BioSounds Logo" is a derivative of two icons created by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">
					www.flaticon.com</a> and licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></h6>
				<h6>"BioSounds Logo" Copyright by <a href="http://www.crazycodelady.com" target="_blank" title="CrazyCodeLady - Noemi Perez">CrazyCodeLady - Noemi Perez</a></h6>
				<h6><a href="#" onClick="window.open('include/copyright.php', 'copyright', 'width=650,height=400,status=yes,resizable=yes,scrollbars=yes')" 
				title="Copyright information of the application">&copy; 2010-2015 LJV</a>. Licensed under the GPLv3</h6>
			</div>
			<div class="col-lg-4 text-right">
				<h6>Project <a href="project" title="About the project"><?php echo $this->projectName;?></a></h6>
				<h6>Sound Files License - <?php echo $this->filesLicense;?>: <?php echo $this->filesLicenseDetail;?></h6>
			</div>
		</div>
	</div>
</footer>
