<base href="http://localhost/biosounds/">

<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Bootstrap theme -->
<link rel="stylesheet" href="assets/css/bootstrap-theme.min.css">

<!-- JQuery UI -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/redmond/jquery-ui.css">

<!-- font-awesome -->
<link rel="stylesheet" href="assets/css/font-awesome.min.css">

<link rel="stylesheet" href="assets/css/jquery.Jcrop.css">

<!-- Custom CSS -->
<link rel="stylesheet" href="assets/css/custom.css">

<link rel="stylesheet" href="assets/plupload/jquery.plupload.queue.css" media="screen">

<script src="http://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>

<script src="assets/plupload/js/plupload.full.min.js"></script>
<script src="assets/plupload/js/jquery.plupload.queue.min.js"></script>
   
