<form action="login/log" method="POST">
  <div class="form-group login-form">
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" id="inputUsername" name="inputUsername" class="form-control input-md" placeholder="Username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" name="inputPassword" class="form-control input-md" placeholder="Password" required>
    <button class="btn btn-md btn-primary" type="submit">Log In</button>
  </div>	        
</form>
