<div class="main">
	<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h1><img src="<?php echo IMAGES_URL;?>biosounds_logo_large.png"></h1>
					<p>BioSounds is the tool for generating, analysing and tagging animal sound spectrograms on the web.</p>
				</div>
			</div>		
		</div>
	</div>
	<div>
		<div class="container">
			<div class="row text-center">
				<h2>Project <?php echo $this->projectName;?></h2>
				<p><?php echo $this->projectDescription;?></p>
			</div>		
			<div class="row">	
				<div class="col-lg-6" style="border-right:1px solid #000;">
					<h3>Participation</h3>
					<p>We are looking for bird call identifiers!</p>
					<p>You need good knowledge of Sumatran bird calls to join the project. If you are qualified and interested, please contact us at kdarras@gwdg.de</p>
					<p>Bird identifiers are hired for whole surveys and remunerated per recording hour.</p>
					<h3>Recordings</h3>
					<p>We have round the clock recordings for a whole year's time from the following locations: secondary forest, jungle rubber, rubber and oil palm plantations, 
					as well as primary and secondary swamp forest and bush swamp. The birds need to be identified in a subset of the data.</p>
					<img src="<?php echo PROJECT_IMAGES_URL;?>beo.jpg" class="img-round center-block">
				</div>
				<div class="col-lg-6">
					<h3>Blog</h3>				

				</div>
			</div>		
		</div>
	</div>
</div>
