<!-- Scripts for JQuery -->

<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js" integrity="sha256-xNjb53/rY+WmG+4L6tTl9m6PpqknWZvRt0rO1SRnJzw="	crossorigin="anonymous"></script>
<!-- Scripts for Bootstrap -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- Scripts for Javascript Click app JCrop -->
<script src="assets/js/jquery.Jcrop.min.js"></script>

<script src="assets/js/functions.js"></script>


