<div id="hiddenForm" class="hidden-form" hidden>
	<form id="uploadSoundForm" method="POST">	
		<div class="row">
			<div class="col-md-8">	
				<div id="file_uploader">You browser doesn't support native upload.</div>		
				<input type="hidden" name="colID" value="<?php echo $this->colID; ?>">
			</div>
			<div class="col-md-4">	
				<div class="form-group form-inline">                                 
					<label for="dateFromFile">Date/Time From File </label>
					<input id="dateFromFile" class="form-control" name="dateFromFile" type="checkbox">
				</div>			
				<div class="form-group">                                 
					<label for="date">Date </label>
					<input id="date" class="form-control" name="date" type="date" placeholder="yyyy-mm-dd">
				</div>	
				<div class="form-group"> 
					<label for="time">Time </label>
					<input id="time" class="form-control" name="time" type="time" placeholder="00:00:00">
				</div>
				<div class="form-group"> 
					<label for="sensor">Sensor </label>
					<select id="sensor" name="sensor" class="form-control">
						<?php echo $this->sensorsList;?>
					</select>
				</div>
				<div class="form-group"> 
					<label for="site">Site </label>
					<select id="site" name="site" class="form-control">
						<?php echo $this->sitesList;?>
					</select>
				</div>
			</div>
		</div>	
		<div class="form-group text-right">	
			<button type="button" class="btn btn-primary open-form">Close</button>
			<button id="save_button" type="submit" class="btn btn-primary" disabled><span class="glyphicon glyphicon-save"></span> Save</button>
		</div>
	</form>		
</div>	
		
<div class="row sound-admin-header">
	<form id="collectionForm" action="admin/sounds" method="POST">
		<div class="col-md-6 text-left">
			<label for="colID">Collection </label>
			<select id="colID" name="colID">
				<?php echo $this->collectionsList;?>
			</select>
		</div>	
	</form>
	<div class="col-md-6 text-right">
		<button type="button" id="upload_btn" class="btn btn-primary btn-sm open-form"></button>
	</div>	
</div>
<table class="table table-condensed table-hover table-sounds save-sound">
	<thead><tr><th>ID</th><th>Original Filename</th><th>Sound Name</th><th>Date</th><th>Time</th><th></th></tr></thead>
	<tbody><?php echo $this->listSounds;?></tbody>
</table>
<div class="row">
	<div class="col-md-12 text-center">
		<ul class="pagination">
			<?php echo $this->paginator;?>
		</ul>
	</div>
</div>
<script>
	$(function() {
		$("#file_uploader").pluploadQueue({
			runtimes : 'html5',
			url : '<?php echo APP_URL;?>/uploaded.php',
			max_file_size : '1000mb',
			chunk_size : '1mb',
			unique_names : false,
			filters : {
				max_file_size : '1000mb',
				mime_types: [
					{title : "Sound files", extensions : "flac,wav,ogg,mp3"}
				]
			},
			init : {	 
				UploadComplete: function(up, files) {
					$("#save_button").toggleDisabled();
				},	  
				Error: function(up, args) {
					showMessage("Error uploading files.");
				}
			}
		});
		
		$('#uploadSoundForm').submit(function(e){
			$('#save_button').toggleDisabled();
			var values = $(this).serialize();
			values["colID"] = $("#collection").val();
			
			$.ajax({
				type: 'POST',
				url: 'ajaxcallmanager.php?class=file&action=save',
				data: values,
				success: function(data){
					$("#hiddenForm").toggle();
					$("#upload_btn").toggle();
			    },
			    error: function(data, error, message){
					showMessage(message, true);
			    }
			});
			e.preventDefault();
		});	
		
		$('.delete_sound').click(function(e){
			if(!confirm('Are you sure you want to delete this sound?')){
			   return false;	
			} 
			
			$(this).attr('disabled', true);
			
			var values = { id: $(this).data("id") };
			$.ajax({
				type: 'POST',
				url: 'ajaxcallmanager.php?class=soundmanager&action=delete',
				data: values,
				success: function(data){
					showMessage(data, true);
			    },
			    error: function(data, error, message){
					showMessage(data.message, true);
			    }
			});
			e.preventDefault();
		});	
		
		$("#colID").change(function(e){
			$("#collectionForm").submit();
		});		
		
		$("#dateFromFile").change(function(e){
			//$("#date").toggleDisabled();
			//$("#time").toggleDisabled();
		});	

		checkUploadProcesses();
	});	

</script>

