<form id="reviewForm">
	<div class="row">
		<div class="col-md-1"><h5 id="state"></h5></div>	
		<div class="col-md-11">
			<div class="form-group form-inline text-right">
				<button type="button" class="btn btn-primary btn-sm" id="review-accept-btn">Accept</button>
				<button type="button" class="btn btn-warning btn-sm" id="review-correct-btn">Correct</button>
				<button type="button" class="btn btn-danger btn-sm" id="review-delete-btn">Delete</button>
			</div>	
		</div>
	</div>		
	<input id='review_animal_id' name='<?php echo $this->animalFN;?>' type='hidden'>
	<input name='<?php echo $this->soundTagFN;?>' type='hidden' value='<?php echo $this->soundTagID;?>'>
	<input id='review_status' name="<?php echo $this->statusFN;?>" type='hidden' value="">
	<div class="form-group" id="review_animal_group">						
		<label for="review_animal_desc">New Review Species</label>						
		<input id="review_animal_desc" class="form-control" type="text" size="30" disabled>
	</div> 
	<div class="form-group">
		<textarea name="<?php echo $this->commentsFN;?>" class="form-control" placeholder="Insert your comments" maxlength="200" col="20" rows="2"></textarea>
	</div>
	<div class="review-table">
		<table class="table table-condensed">
			<thead><tr><th>Reviewer</th><th>Status</th><th>Species</th><th>Date</th></tr></thead>
			<tbody><?php echo $this->reviewsList;?></tbody>
		</table>
	</div>
</form>

<script>
	$(function(){	
		$("#reviewForm :input").not("#review_animal_desc").prop("disabled", <?php echo $this->disableReviewForm;?>);
				
		$('#review_animal_desc').autocomplete({
			source:'ajaxcallmanager.php?class=animal&action=getAnimalList', minLength:3,
			change: function (event, ui) {
				if(!ui.item){
					$('#review_animal_desc').val('');
					$('#review_animal_id').val('');
				} 
			},
			select: function (event, ui) {
				event.preventDefault();
				var label = ui.item.label.split('(')[0];
				$('#review_animal_desc').val(label);
				$('#review_animal_id').val(ui.item.value);
		}});
		
		$("#review-accept-btn").click(function(e){
			$('#review_animal_desc').prop('disabled', "disabled");
			$('#review_animal_id').val("");
			$('#review_status').val(1);
			$('#state').html("Accepted");
			e.preventDefault();
		});	
		
		$("#review-correct-btn").click(function(e){
			$('#review_animal_desc').prop('disabled', function(i, v) { return !v; });
			$('#review_status').val(2);
			$('#state').html("Corrected");
			e.preventDefault();
		});
		
		$("#review-delete-btn").click(function(e){
			$('#review_animal_desc').prop('disabled', "disabled");
			$('#review_animal_id').val("");
			$('#review_status').val(3);
			$('#state').html("Deleted");
			e.preventDefault();
		});
		
		$('#reviewForm').submit(function(e) {
			$.ajax({
				type: 'POST',
				url: 'ajaxcallmanager.php?class=tagreview&action=save',
				data: $(this).serialize(),
				success: function(data)
			    {	 
					if(data.status == 'error'){
						showMessage(data.message, true);						
					}
					else {
						showMessage("Changes saved");
					} 	
			    },
			    error: function(data, error, message)
			    {
					showMessage(message, true);
			    }
			});
			e.preventDefault();
		});
	});
	
	function submitReviewForm(closeModal = true){
		$('#review_animal_group').removeClass('has-error');
		$('#review_animal_help').remove();		
		if($('#review_status').val() == 2 && $('#review_animal_id').val() == ''){
			$('#review_animal_group').addClass('has-error');
			$('#review_animal_desc').after('<span id="review_animal_help" class="help-block">Please select an animal from the list.</span>');
		} else {
			$('#reviewForm').submit();
			if(closeModal === true)
				$('#modal-div').modal('hide');
		}
	}	

</script>
