<header>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class='navbar-brand' href="<?php echo APP_URL?>" alt='BioSounds' title="BioSounds"><img src="<?php echo LOGO?>"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li class='dropdown'><a aria-expanded='true' tabindex='0' data-toggle='dropdown' data-submenu='' href='#'>Open Collections<span class='caret'></span></a>
                  <ul class='dropdown-menu'>
                      <li><a href="<?php echo APP_URL?>/collection/show/1/1">Demo</a></li>
                      <li><a href="<?php echo APP_URL?>/collection/show/3/1">Berbak NP phase 1 and 2 </a></li>
                      <li><a href="<?php echo APP_URL?>/collection/show/18/1">Reference collection (amphibians)</a></li>
                      <li><a href="<?php echo APP_URL?>/collection/show/31/1">Microphone SNR</a></li>
                  </ul>
              </li>
              <?php echo $this->extraMenu;?>
              <li><a href="<?php echo APP_URL?>/project">Project</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">   
			  <li><a><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search</a></li> 
			  <?php echo $this->topRightMenu;?> 	
          </ul>
        </div>
      </div>
    </nav>
</header>
