<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Edit Password for User <?php echo $this->username;?></h4>
			</div>
			<div class="modal-body">
				<form id="pwdForm">
					<input name="itemID" type="hidden" value="<?php echo $this->userID;?>">
					<div class="form-group" id="admin_pwd_group">						
						<label for="admin_pwd">Administrator Password</label>		
						<input id="admin_pwd" name="admin_pwd" class="form-control" type="password" required>
					</div> 	
					<div class="form-group" id="new_password1">
						<label for="user_new_pwd1">New Password</label>		
						<input id="user_new_pwd1" name="<?php echo $this->userPasswordLabel;?>_password" class="form-control" type="password" required>
					</div> 
					<div class="form-group" id="new_password2">	
						<label for="user_new_pwd2">Retype New Password</label>		
						<input id="user_new_pwd2" class="form-control" type="password" required>
					</div> 
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" id="bsave">Save</button>	
			</div>
		</div>
	</div>
</div>

<script>
	$(function(){	
		$('#pwdForm').submit(function(e) {
			$.ajax({
				type: 'POST',
				url: 'ajaxcallmanager.php?class=user&action=save',
				data: $(this).serialize(),
				success: function(data)
			    {	 
					if(data.status == 'error'){
						showMessage(data.message, true);						
					}
					else {
						showMessage("Changes saved");
					} 	
					$('#modal-div').modal('hide');				
			    },
			    error: function(data, error, message)
			    {
					showMessage(message, true);
					$('#modal-div').modal('hide');
			    }
			});
			e.preventDefault();
		});
		
		$('#bsave').click(function() {
			checkForm();	
		});
	});	
	
	function clearMessages(){
		$('#password1_help').remove();
		$('#new_password1').removeClass('has-error');
		$('#password2_help').remove();
		$('#new_password2').removeClass('has-error');
		$('#match_password_help').remove();
	}
	
	function checkForm(){
		clearMessages();
		if($('#admin_pwd').val() == ""){
			$('#admin_pwd_group').addClass('has-error');
			$('#admin_pwd').after('<span id="password1_help" class="help-block">Please enter the administrator password.</span>');
		} else if($('#user_new_pwd1').val() == ""){
			$('#new_password1').addClass('has-error');
			$('#user_new_pwd1').after('<span id="password1_help" class="help-block">Please enter a password.</span>');
		} else if($('#user_new_pwd2').val() == ""){
			$('#new_password2').addClass('has-error');
			$('#user_new_pwd2').after('<span id="password2_help" class="help-block">Please retype the password.</span>');
		} 
		else if($('#user_new_pwd1').val() != $('#user_new_pwd2').val()){
			$('#new_password2').addClass('has-error');
			$('#user_new_pwd2').after('<span id="match_password_help" class="help-block">New passwords do not match.</span>');
		}
		else {
			$('#bsave').attr('disabled', true);
			$('#pwdForm').submit();
		}
	}

</script>
